nnotations:
  - border_color: '#00000000'
    border_style: ''
    color: '#000000'
    rotation: 0
    text_bold: false
    text_content: |
      Lo0 2001:DB8:CAFE:6::1/64
      192.168.6.1/24
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -680.0
    y1: 80.0
    z_index: 0
  - border_color: '#00000000'
    border_style: ''
    color: '#000000'
    rotation: 0
    text_bold: false
    text_content: |-
      Lo1: 2001:DB8:CAFE:1::1/64
           192.168.1.1/24
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -680.0
    y1: -40.0
    z_index: 1
  - border_color: '#00000000'
    border_style: ''
    color: '#000000'
    rotation: 0
    text_bold: false
    text_content: |-
      E0/0 2001:DB8:CAFE:2::1/64
      192.168.2.1/30
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -440.0
    y1: -120.0
    z_index: 2
  - border_color: '#00000000'
    border_style: ''
    color: '#000000'
    rotation: 0
    text_bold: false
    text_content: |-
      Link-Local: R1->FE80::1
      R2->FE80::2
      R3->FE80::3
      R4->FE80::4
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -320.0
    y1: 80.0
    z_index: 3
  - border_color: '#00000000'
    border_style: ''
    color: '#070606'
    rotation: 0
    text_bold: false
    text_content: |-
      Lo0: 2001:DB8:CAFE:3::1/64
           192.168.3.1 /24
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -80.0
    y1: -320.0
    z_index: 4
  - border_color: '#00000000'
    border_style: ''
    color: '#000000'
    rotation: 0
    text_bold: false
    text_content: |-
      E0/0 2001:DB8:CAFE:2::2/64
      192.168.2.2 /30
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -400.0
    y1: -240.0
    z_index: 5
  - border_color: '#D54141'
    border_style: ''
    color: '#FFFFFF00'
    rotation: 60
    thickness: 1
    type: ellipse
    x1: -323.7212410771394
    y1: -96.5673301688139
    x2: 140.0
    y2: 284.37822191934765
    z_index: 6
  - border_color: '#00000000'
    border_style: ''
    color: '#080808'
    rotation: 0
    text_bold: false
    text_content: EIGRP
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -400.0
    y1: -160.0
    z_index: 7
  - border_color: '#00000000'
    border_style: ''
    color: '#0C0B0B'
    rotation: 0
    text_bold: false
    text_content: |-
      E0/1: 2001:DB8:CAFE:4::1/64
            192.168.4.1 /30
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -40.0
    y1: -200.0
    z_index: 8
  - border_color: '#C51A1A'
    border_style: ''
    color: '#00000000'
    rotation: 62
    thickness: 1
    type: ellipse
    x1: 15.700262844779772
    y1: -93.15786957488754
    x2: 210.66690017820696
    y2: 86.97927556449724
    z_index: 9
  - border_color: '#00000000'
    border_style: ''
    color: '#000000'
    rotation: 0
    text_bold: false
    text_content: area0
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 40.0
    y1: -80.0
    z_index: 10
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: ''
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 40.0
    y1: 160.0
    z_index: 11
  - border_color: '#00000000'
    border_style: ''
    color: '#000000'
    rotation: 0
    text_bold: false
    text_content: |-
      E0/1:2001:DB8:CAFE:4::2/64
           192.168.4.2 /30
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 40.0
    y1: -40.0
    z_index: 12
  - border_color: '#00000000'
    border_style: ''
    color: '#080707'
    rotation: 0
    text_bold: false
    text_content: |-
      Lo0: 2001:DB8:99:1::1/64
      192.168.99.1 /24
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 480.0
    y1: 200.0
    z_index: 13
  - border_color: '#BD1B1B'
    border_style: ''
    color: '#FFFFFF00'
    rotation: 0
    thickness: 1
    type: ellipse
    x1: 420.0
    y1: 120.0
    x2: 300.0
    y2: 80.0
    z_index: 14
  - border_color: '#00000000'
    border_style: ''
    color: '#808080FF'
    rotation: 0
    text_bold: false
    text_content: ''
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 280.0
    y1: -160.0
    z_index: 15
  - border_color: '#00000000'
    border_style: ''
    color: '#000000'
    rotation: 0
    text_bold: false
    text_content: |-
      E0/1: 2001:DB8:FEED:77::1/64
      192.168.77.1 /30
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 200.0
    y1: 80.0
    z_index: 16
  - border_color: '#00000000'
    border_style: ''
    color: '#0B0A0A'
    rotation: 0
    text_bold: false
    text_content: |-
      E0/0:2001:DB8:FEED:77::2/64
       192.168.77.2 /30
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: 520.0
    y1: 80.0
    z_index: 17
  - border_color: '#00000000'
    border_style: ''
    color: '#000000'
    rotation: 0
    text_bold: false
    text_content: |-
      OSPF
      (IPV4,IPV6)
    text_font: monospace
    text_italic: false
    text_size: 9
    text_unit: pt
    thickness: 1
    type: text
    x1: -80.0
    y1: 0.0
    z_index: 19
  - border_color: '#808080FF'
    border_radius: 0
    border_style: ''
    color: '#F3080800'
    rotation: 0
    thickness: 1
    type: rectangle
    x1: -720.0
    y1: -320.0
    x2: 920.0
    y2: 560.0
    z_index: 20
  - border_color: '#00000000'
    border_style: ''
    color: '#000000'
    rotation: 0
    text_bold: false
    text_content: |-
      BBCO
      AS65000
    text_font: monospace
    text_italic: false
    text_size: 12
    text_unit: pt
    thickness: 1
    type: text
    x1: -680.0
    y1: -280.0
    z_index: 21
smart_annotations: []
nodes:
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          hostname R2
          !
          # Loopback Interface for Testing
          interface Loopback0
           ip address 192.168.3.1 255.255.255.0
           ipv6 address 2001:DB8:CAFE:3::1/64
          !
          # Ethernet0/0 Connection to R1
          interface Ethernet0/0
           ip address 192.168.2.2 255.255.255.252
           ipv6 address 2001:DB8:CAFE:2::2/64
           no shutdown
          !
          # Ethernet0/1 Connection to R3
          interface Ethernet0/1
           ip address 192.168.4.1 255.255.255.252
           ipv6 address 2001:DB8:CAFE:4::1/64
           no shutdown
          !
          # Enable EIGRP (IPv4)
          router eigrp 100
           network 192.168.2.0 0.0.0.3
          !
          # Enable OSPF (IPv4)
          router ospf 1
           network 192.168.3.0 0.0.0.255 area 0
           network 192.168.4.0 0.0.0.3 area 0
          !
          # Enable EIGRP (IPv6)
          ipv6 router eigrp 100
           no shutdown
          !
          # Enable OSPF (IPv6)
          ipv6 router ospf 1
           router-id 2.2.2.2
           exit
          !
          # Enable BGP (IPv4)
          router bgp 65000
           neighbor 192.168.2.1 remote-as 65000
           neighbor 192.168.4.2 remote-as 65000
           network 192.168.2.0 mask 255.255.255.252
           network 192.168.3.0 mask 255.255.255.0
           network 192.168.4.0 mask 255.255.255.252
          !
          # Enable IPv6 Routing
          ipv6 unicast-routing
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n0
    image_definition: null
    label: R2
    node_definition: iol-xe
    parameters: {}
    ram: null
    tags: []
    x: -80
    y: -280
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: Ethernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: Ethernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: Ethernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: Ethernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          hostname R3
          !
          # Loopback Interface for Testing
          interface Loopback0
           ip address 192.168.5.1 255.255.255.0
           ipv6 address 2001:DB8:CAFE:5::1/64
          !
          # Ethernet0/0 Connection to R2
          interface Ethernet0/0
           ip address 192.168.4.2 255.255.255.252
           ipv6 address 2001:DB8:CAFE:4::2/64
           no shutdown
          !
          # Ethernet0/1 Connection to R4
          interface Ethernet0/1
           ip address 192.168.77.1 255.255.255.252
           ipv6 address 2001:DB8:FEED:77::1/64
           no shutdown
          !
          # Enable OSPF (IPv4)
          router ospf 1
           network 192.168.4.0 0.0.0.3 area 0
           network 192.168.5.0 0.0.0.255 area 0
          !
          # Enable OSPF (IPv6)
          ipv6 router ospf 1
           router-id 3.3.3.3
           exit
          !
          # Enable BGP (IPv4)
          router bgp 65000
           neighbor 192.168.4.1 remote-as 65000
           neighbor 192.168.77.2 remote-as 65000
           network 192.168.4.0 mask 255.255.255.252
           network 192.168.5.0 mask 255.255.255.0
           network 192.168.77.0 mask 255.255.255.252
          !
          # Enable IPv6 Routing
          ipv6 unicast-routing
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n1
    image_definition: null
    label: R3
    node_definition: iol-xe
    parameters: {}
    ram: null
    tags: []
    x: 80
    y: 120
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: Ethernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: Ethernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: Ethernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: Ethernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          hostname R4
          !
          # Loopback Interface for Testing
          interface Loopback0
           ip address 192.168.99.1 255.255.255.0
           ipv6 address 2001:DB8:99:1::1/64
          !
          # Ethernet0/0 Connection to R3
          interface Ethernet0/0
           ip address 192.168.77.2 255.255.255.252
           ipv6 address 2001:DB8:FEED:77::2/64
           no shutdown
          !
          # Enable OSPF (IPv4)
          router ospf 1
           network 192.168.77.0 0.0.0.3 area 0
           network 192.168.99.0 0.0.0.255 area 0
          !
          # Enable OSPF (IPv6)
          ipv6 router ospf 1
           router-id 4.4.4.4
           exit
          !
          # Enable BGP (IPv4)
          router bgp 65000
           neighbor 192.168.77.1 remote-as 65000
           network 192.168.77.0 mask 255.255.255.252
           network 192.168.99.0 mask 255.255.255.0
          !
          # Enable IPv6 Routing
          ipv6 unicast-routing
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n2
    image_definition: null
    label: R4
    node_definition: iol-xe
    parameters: {}
    ram: null
    tags: []
    x: 760
    y: 120
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: Ethernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: Ethernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: Ethernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: Ethernet0/3
        mac_address: null
        slot: 3
        type: physical
  - boot_disk_size: null
    configuration:
      - name: ios_config.txt
        content: |-
          hostname R1
          !
          # Loopback Interfaces for Testing
          interface Loopback0
           ip address 192.168.6.1 255.255.255.0
           ipv6 address 2001:DB8:CAFE:6::1/64
          !
          interface Loopback1
           ip address 192.168.1.1 255.255.255.0
           ipv6 address 2001:DB8:CAFE:1::1/64
          !
          # Ethernet0/0 Connection to R2 (UPDATED)
          interface Ethernet0/0
           ip address 192.168.2.1 255.255.255.252
           ipv6 address 2001:DB8:CAFE:2::1/64
           no shutdown
          !
          # Enable EIGRP (IPv4)
          router eigrp 100
           network 192.168.1.0 0.0.0.255
           network 192.168.2.0 0.0.0.3
          !
          # Enable EIGRP (IPv6)
          ipv6 router eigrp 100
           no shutdown
          !
          # Enable IPv6 Routing
          ipv6 unicast-routing
    cpu_limit: null
    cpus: null
    data_volume: null
    hide_links: false
    id: n3
    image_definition: null
    label: R1
    node_definition: iol-xe
    parameters: {}
    ram: null
    tags: []
    x: -480
    y: 40
    interfaces:
      - id: i0
        label: Loopback0
        mac_address: null
        type: loopback
      - id: i1
        label: Ethernet0/0
        mac_address: null
        slot: 0
        type: physical
      - id: i2
        label: Ethernet0/1
        mac_address: null
        slot: 1
        type: physical
      - id: i3
        label: Ethernet0/2
        mac_address: null
        slot: 2
        type: physical
      - id: i4
        label: Ethernet0/3
        mac_address: null
        slot: 3
        type: physical
links:
  - id: l0
    n1: n3
    n2: n0
    i1: i1
    i2: i1
    conditioning: {}
    label: iol-0-Ethernet0/0<->iol-1-Ethernet0/0
  - id: l1
    n1: n0
    n2: n1
    i1: i2
    i2: i1
    conditioning: {}
    label: iol-1-Ethernet0/1<->iol-2-Ethernet0/0
  - id: l2
    n1: n1
    n2: n2
    i1: i2
    i2: i1
    conditioning: {}
    label: iol-2-Ethernet0/1<->iol-3-Ethernet0/0
lab:
  description: ''
  notes: ''
  title: Lab at Wed 16:21 PM
  version: 0.3.0
